# Generated by Django 4.0.6 on 2022-07-13 12:43

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgName', models.CharField(max_length=100)),
                ('imgUrl', models.CharField(max_length=1000)),
                ('imgDesc', models.CharField(max_length=1000)),
                ('imgDate', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='imgName', unique=True)),
            ],
        ),
    ]
